config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'searchs#new'
  get '/search', to: 'searchs#search', as: :search
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searchs_controller.rb
require 'search'
class SearchsController < ApplicationController
  def search
    search_engine = Search.engine_for(params[:e])
    @search_results = Search.new(search_engine).find_results_for(params[:q])
    respond_to do |format|
      format.html
      format.json { render json: { results: @search_results } }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>ChallengeSynack</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    </head>

    <body>


        <div class="col-lg-8 mx-auto p-3 py-md-5">
            <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
                <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
                    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
                    <span class="fs-4">Search Challenge</span>
                </a>
            </header>

            <main>
                <%= yield %>
            </main>
            <footer class="pt-5 my-5 text-muted border-top">
                Search challenge 2022.
            </footer>
        </div>
    </body>
</html>

app/views/searchs/new.html.erb
<h1>Search what you want:</h1>
<div class="mb-5">
    <%= form_tag(search_path, method: :get) do |f| %>
        <div class="form-group">
            <select name="e">
                <option value="google">Google</option>
                <option value="bing">Bing</option>
                <option value="both">Google + Bing</option>
            </select>
        </div>
        <div class="form-group">
            <%= text_field_tag(:q, params[:q], class: 'form-control') %> <br />
        </div>

        <%= submit_tag 'Search', class: 'btn btn-primary btn-lg px-4' %>
    <% end %>
</div>

app/views/searchs/search.html.erb
<% if @search_results.blank? %>
    <h1>No Results</h1>
<% end %>


<% unless @search_results.blank? %>
<h1 class="mb-5">Results: </h1>
<table class="table">
    <tr>
        <th>title</th>
        <th>link</th>
    </tr>
    <% @search_results.each do |r| %>
        <tr>
            <td><%= r.title %></td>
            <td><a href="<%= r.link %>"> <%= r.link %> </a></td>
        </tr>
    <% end %>
</table>
<% end %>